require 'rake_pipeline'

include Rake::Pipeline

$message ||= STDIN.read.chomp

desc "Writing the message"
step_def :message do
  sleep 2
  $message
end

desc "Computing the length"
step_def :length do
  sleep 2
  info 'length' => input.length
  nil
end

desc "Writing reverse message"
step_def :reverse do
  sleep 2
  input(:message).reverse
end
